USE  TECHBROS;
ALTER TABLE PWDS DROP COLUMN LOCTION;
DESC PWDS;
ALTER TABLE PWDS CHANGE YOS YOE VARCHAR(50) NOT NULL;
DESC PWDS;
ALTER TABLE PWDS RENAME TO PYTHON_WITH_DATA_SCIENCE;
DESC PYTHON_WITH_DATA_SCIENCE;
DROP TABLE PYTHON_WITH_DATA_SCIENCE;


CREATE TABLE PWDS(ID INT NOT NULL, SNAME VARCHAR(255) NOT NULL, AGE INT NOT NULL, GENDER VARCHAR(10) NOT NULL,
                  SLEVEL VARCHAR(25) NOT NULL, PHONENUMBER VARCHAR(45) NOT NULL, YOS VARCHAR(45) NOT NULL, LOCATION VARCHAR(255) NOT NULL);
                  
                  
ALTER TABLE PWDS CHANGE YOS YOE VARCHAR(50) NOT NULL;
DESC PWDS;

SELECT * FROM PWDS;

INSERT INTO PWDS(ID,SNAME,AGE,GENDER,SLEVEL,PHONENUMBER,YOE,LOCATION)VALUES
(1, 'JOHN ARMSTADRAM', 45, 'MALE', 'EXPERT','+155566666336', '10 YEARS','CHICAGO'),
(2, 'WESLEY OBARN', 27 , 'MALE', 'JUNIOR', '+55225255555555', '2 YEARS', 'TEXAS'),
(3, 'VICTORIA RECCE',32, 'FEMALE', 'INTERMEDIATE', '+33895678555', '5 YEARS', 'PARIS'),
(4, 'AINA JAMES',50,'MALE','EXPEERT','+2345888888555','20 YEARS','LAGOS'),
(5, 'SHASHSA MUDEISE',29,'FEMALE','INTERMEDIATE','+2745888888555','6 YEARS','CAPE TOWN');


SELECT * FROM PWDS;
UPDATE PWDS SET AGE = 42 WHERE ID = 1;
SELECT * FROM PWDS;

SELECT SNAME FROM PWDS;
SELECT * FROM PWDS WHERE ID =2;

DELETE FROM PWDS WHERE ID = 5;
SELECT * FROM PWDS;
DELETE FROM PWDS WHERE ID = 5;
SELECT * FROM PWDS;

CREATE INDEX GENDER ON PWDS(GENDER);
SHOW INDEXES FROM PWDS;
SELECT * FROM PWDS WHERE GENDER ='MALE';
DROP INDEX GENDER ON PWDS;
SHOW INDEXES FROM PWDS;


